server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka


  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.127:3306/sanzu?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456